### ISSUE TITLE
[BUG] The responsive design for desktop screens 1150px to 1475px wide have some elements truncated

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/Lahouiti_Younes_12_01012023#6]
The responsive design for desktop screen between this range: [1150, 1475] 

Have the macronutrients cards (key data cards in the code) truncated or completely cut off from the screen view: 
![image](https://user-images.githubusercontent.com/78600723/212319056-bfd5a881-3946-4414-8742-6282e9341848.png)

**Comment by LePhenix47** [comment]
Possible fix by adding an extra media query for small desktop monitors with SASS, also here's a possible UI fix:

Add a `padding` to the bottom of the sidebar to avoid the text cutting off

Change the `gap` and  `flex-direction` to a reversed column to the container: `.profile__data-container`

Set the `width` to take 100% of the space available for the `.key-data-card`

Modify the margin and the alignment of the text for `.key-data-card__text-container`

*Example:*

```css

/*
//Custom media queries are still experimental in CSS as of 13-01-2023 → not supported yet

//Range media queries are actually supported across most browsers at the exception of Safari
*/
@custom-media --small-desktop ((1150px <= width <= 1475px));

/*
//Example in CSS, will do in SASS in the app
*/
@media screen and --small-desktop {

    .side-bar{
      padding-block-end: 40px; /* padding-bottom works as well */
    }

    .profile__data-container{
       flex-direction: column-reverse;
       gap: 25px;
    }
    
    .key-data-card{
       width: 100%;
    }
    
    .key-data-card__text-container{
       margin: auto;
       text-align: center;
    }

}
```


*Result:*
![image](https://user-images.githubusercontent.com/78600723/212319710-9f2cf6b2-dad9-4358-b71d-a666111f9fef.png)
